spring:
  profiles:
    active: local

  datasource:
    url: ${DB_URL:jdbc:h2:mem:test}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: ${SQL_INIT_MODE:always}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: ${JPA_DDI:false}

  data:
    redis:
      host: ${DATA_REDIS_HOST:localhost}
      port: 6379

  config:
    import: optional:file:.env[.properties]

jwt:
  access:
    expiration: 1800000 #30분
  refresh:
    expiration: 1209600000 #2주
  security:
    secretKey: my-custom-secret-key-that-is-very-long

naver:
  book:
    id: ${NAVER_BOOK_ID:your_id}
    secret: ${NAVER_BOOK_SECRET:your_key}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

firebase:
  service:
    key: /firebase/readnshare-firebase-adminsdk.json



springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html